[package]
name = "kava"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.6.0"
tokio = { version = "1.37.0", features = ["full"] }
